CREATE DATABASE Repository;
USE Repository;
CREATE TABLE Radar_Setup (
 ID INTEGER PRIMARY KEY,
 TIMESPOT DATETIME,
 SENSOR1_DISTANCE FLOAT,
 SENSOR2_DISTANCE FLOAT,
 SENSOR3_DISTANCE FLOAT,
 ANGLEH1 FLOAT,
 ANGLEH2 FLOAT,
 ANGLEV FLOAT,
 RADAR_IMAGE VARCHAR(255)
 );
 
